### PR TITLE
Signer guide updates

### PR DESCRIPTION
**Pull request by ipopescu**
I am working on removing the Signer user guide from the Casper node core documentation found [here](https://docs.casperlabs.io/workflow/signer-guide/). I wanted to place the content here, so it doesn't get lost. 

Screen Shot 2023-01-24 at 11 46 05 PM

### CODE REVIEW

**Comment by ipopescu** [comment]
@mrkara this is ready for review. Thanks!

**Comment by mrkara** [comment]
Hi @ipopescu ! Thanks a lot for the great PR!

Could you please add your changes to the `src` dir instead of the `docs` dir, and then run the `build.sh` script?

Feel free to check out the [contribution guidelines](https://github.com/make-software/how-to-casperlabs/blob/master/CONTRIBUTING.md), and please don't hesitate to ping me if there is anything I can help with.

**Comment by ipopescu** [comment]
Hi @mrkara, thank you for the feedback. I have made the updates and rand the build.sh script. I also read the contribution guidelines; sorry for missing these initially.
Is there a way to run the site locally? I have Ruby and Jekyll installed, but I didn't know how to proceed. Thanks!

**Comment by mrkara** [comment]
Hi @ipopescu , thank you for the updates. No worries. We should probably have a link from the README to the contribution guidelines.

- You can have your clone deployed to GH Pages to see the results. (This is what I prefer to avoid installing dependencies locally, and adding extra config for local run.)

**OR**

- You can;
  - Add a `Gemfile` to your local clone with the content
    ```
    source "https://rubygems.org"
    gem "github-pages", group: :jekyll_plugins
    gem "webrick", "~> 1.7"
    ```
  - Then run these commands in the given order:
    ```
    bundle config set --local path 'vendor/bundle'
    bundle install
    bundle exec jekyll serve
    ```
    * The first two commands are meant to be run only once unless you delete the downloaded dependencies inside your clone dir.

**Comment by ipopescu** [comment]
Thanks, @mrkara. I was able to run the site locally and updated the content based on testing it. I've attached a PDF of the local site: [Signer Guide _ Casper How-To Guides.pdf](https://github.com/make-software/how-to-casperlabs/files/10494615/Signer.Guide._.Casper.How-To.Guides.pdf).

**Comment by mrkara** [comment]
@ipopescu Thank you! I see "A short documentation aimed to help newcomers to get started
with Casperlabs validator node" as subtitle at the top. Is that a leftover?

**Comment by ipopescu** [comment]
> @ipopescu Thank you! I see "A short documentation aimed to help newcomers to get started with Casperlabs validator node" as subtitle at the top. Is that a leftover?

This is auto-generated when I run the site locally, but I don't know where it comes from. I have not added this tagline to the Signer guide.

**Comment by mrkara** [comment]
> > @ipopescu Thank you! I see "A short documentation aimed to help newcomers to get started with Casperlabs validator node" as subtitle at the top. Is that a leftover?
> 
> This is auto-generated when I run the site locally, but I don't know where it comes from. I have not added this tagline to the Signer guide.

@ipopescu Weird. I can't find it even by a git grep search on the entire repo.

**Comment by ipopescu** [comment]
Yes, I also spent some time looking for the source, and I couldn't figure it out. But since I haven't changed any of the infrastructure, I don't expect this header to be generated in production.

**Review by mrkara — APPROVED** [review]
LGTM. @ipopescu Thank you!

**Pull request merged**
